import { Platform } from 'react-native';

const palette = {
  primary: '#5D1A1A',
  primaryMuted: '#7A3B3B',
  secondary: '#343A30',
  tertiary: '#D9C5B2',
  neutral: '#1C1C1C',
  white: '#FFFFFF',
  cream1: '#F5F2EE',
  cream2: '#EDEBE7',
  cream3: '#FAF8F5',
  warmGray1: '#5E5954',
  warmGray2: '#8E8882',
  warmGray3: '#B8B2AC',
  separator: 'rgba(28, 28, 28, 0.06)',
  separatorDark: 'rgba(28, 28, 28, 0.10)',
  success: '#2D9B4E',
  warning: '#E88D00',
  danger: '#C0392B',
};

export const Colors = {
  light: {
    text: palette.neutral,
    textSecondary: palette.warmGray1,
    textTertiary: palette.warmGray2,
    background: palette.cream1,
    surface: palette.cream2,
    surfaceElevated: palette.cream3,
    accent: palette.primary,
    accentMuted: palette.primaryMuted,
    tint: palette.primary,
    icon: palette.warmGray2,
    tabIconDefault: palette.warmGray3,
    tabIconSelected: palette.primary,
    card: palette.cream3,
    border: palette.separator,
    separator: palette.separatorDark,
    success: palette.success,
    warning: palette.warning,
    danger: palette.danger,
  },
  dark: {
    text: palette.neutral,
    textSecondary: palette.warmGray1,
    textTertiary: palette.warmGray2,
    background: palette.cream1,
    surface: palette.cream2,
    surfaceElevated: palette.cream3,
    accent: palette.primary,
    accentMuted: palette.primaryMuted,
    tint: palette.primary,
    icon: palette.warmGray2,
    tabIconDefault: palette.warmGray3,
    tabIconSelected: palette.primary,
    card: palette.cream3,
    border: palette.separator,
    separator: palette.separatorDark,
    success: palette.success,
    warning: palette.warning,
    danger: palette.danger,
  },
};

export const Fonts = Platform.select({
  ios: {
    display: 'Manrope_700Bold',
    body: 'Manrope_400Regular',
    bodyMedium: 'Inter_500Medium',
    serif: 'New York',
    sans: 'Manrope_400Regular',
    rounded: 'Manrope_600SemiBold',
    mono: 'Menlo',
  },
  default: {
    display: 'Manrope_700Bold',
    body: 'Manrope_400Regular',
    bodyMedium: 'Inter_500Medium',
    serif: 'serif',
    sans: 'Manrope_400Regular',
    rounded: 'Manrope_600SemiBold',
    mono: 'monospace',
  },
});

export const Layout = {
  radiusXl: 24,
  radiusLg: 18,
  radiusMd: 14,
  radiusSm: 10,
  radiusXs: 6,
  gutter: 20,
  gap: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
  },
};

export const Shadows = {
  sm: {
    shadowColor: '#1B1B1B',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 1,
  },
  md: {
    shadowColor: '#1B1B1B',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 3,
  },
  lg: {
    shadowColor: '#1B1B1B',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 6,
  },
  accent: {
    shadowColor: '#400408',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 16,
    elevation: 4,
  },
};
